 {
  "mode.normal.paste_and_go": "Q",
  "mode.normal.paste_and_go_in_tab": "q",
  "mode.normal.copy_current_url": "w yy",
  "mode.normal.history_back": "z",
  "mode.normal.history_forward": "c",
  "mode.normal.reload_all": "t",
  "mode.normal.reload_all_force": "T",
  "mode.normal.stop": "!",
  "mode.normal.stop_all": "@",
  "mode.normal.scroll_page_down": "<space> b",
  "mode.normal.scroll_page_up": "<s-space> u",
  "mode.normal.scroll_half_page_up": "s",
  "mode.normal.tab_new": "a",
  "mode.normal.tab_new_after_current": "",
  "mode.normal.tab_duplicate": "yt ya",
  "mode.normal.tab_select_previous": "J    gT A",
  "mode.normal.tab_select_next": "K    gt D",
  "mode.normal.tab_move_forward": "gK S",
  "mode.normal.follow_in_focused_tab": "",
  "mode.normal.follow_in_window": "<c-Q>",
  "mode.normal.follow_multiple": "<c-q>",
  "mode.normal.follow_previous": "[ 1",
  "mode.normal.follow_next": "] 2",
  "mode.caret.move_word_left": "b e"
}
