# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=/home/raitaro/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="robbyrussell"
ZSH_THEME="powerlevel9k/powerlevel9k"

# Custom stuff for 9k
POWERLEVEL9K_MODE="nerdfont-complete"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="▶ "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""

# Custom icons
POWERLEVEL9K_CUSTOM_RAITARO="echo Raitaro +"
POWERLEVEL9K_CUSTOM_RAITARO_BACKGROUND=010

POWERLEVEL9K_CUSTOM_REIKA="echo Reika ="
POWERLEVEL9K_CUSTOM_REIKA_BACKGROUND=005

POWERLEVEL9K_CUSTOM_PLUS="echo +"
POWERLEVEL9K_CUSTOM_PLUS_BACKGROUND=008

POWERLEVEL9K_CUSTOM_EQ="echo ="
POWERLEVEL9K_CUSTOM_EQ_BACKGROUND=008

POWERLEVEL9K_CUSTOM_LOVE="echo "
POWERLEVEL9K_CUSTOM_LOVE_BACKGROUND=009

# Battery
POWERLEVEL9K_BATTERY_LOW_FOREGROUND='red'
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='10'
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='blue'
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='green'
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND='yellow'

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time battery)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_raitaro custom_reika custom_love dir vcs)

# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

############################################################################################################
# From my bashrc
############################################################################################################

# locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8


# set -o vi
export MANPAGER="/bin/sh -c \"col -b | vim --not-a-term -c 'set ft=man ts=8 nomod nolist noma' -\""

# For waifu2x
export TORCH_ROOT=~/torch

WAIFU2X_DIR=~/waifu2x
waifu2x()
{
    th ${WAIFU2X_DIR}/waifu2x.lua -model_dir ${WAIFU2X_DIR}/models/anime_style_art_rgb $@
}
waifu2x_photo()
{
    th ${WAIFU2X_DIR}/waifu2x.lua -model_dir ${WAIFU2X_DIR}/models/photo $@
}

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-thing)"
fi

# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

# The default umask is now handled by pam_umask.
# See pam_umask(8) and /etc/login.defs.

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
    
# Bash insulter/cute
if [ -f /etc/bash.command-not-found ]; then
    . /etc/bash.command-not-found
fi

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx

alias install="sudo apt-get install"
alias remove="sudo apt-get remove"
alias fremove="sudo apt-get purge --auto-remove"
alias update="sudo apt-get upgrade -y && sudo apt-get update && sudo apt-get dist-upgrade"
alias qupdate="sudo apt-get upgrade -y"
alias fupdate="sudo apt-get dist-upgrade"
alias clean="sudo apt-get autoclean && sudo apt-get autoremove"
alias cute="sudo wget -O /etc/bash.command-not-found https://raw.githubusercontent.com/RaitaroH/bash-anime-girl/master/src/bash.command-not-found"
alias tvdisable="sudo teamviewer --daemon disable"
alias tvenable="sudo teamviewer --daemon enable"
alias cmatrix="cmatrix -a -C cyan"
alias ll="ls -l"
alias la="ls -a"
alias mu="WallpaperSwicher --most-used"
alias mn="WallpaperSwicher -n"
alias mp="WallpaperSwicher -p"
alias grep="grep --color=auto"
alias skwrite="SUDO_EDITOR=kwrite sudoedit"
alias ksudo="kdesudo"
alias pdf="convert *.jpeg"
alias pdfp="convert *.png"
alias v="vim"

# More configs at ~/.config/youtube-dl/config
alias ymp3="youtube-dl --extract-audio --audio-format mp3 --audio-quality 0"
alias yost_numbering="youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 --yes-playlist -o '/media/raitaro/HDD/Muzica/Anime/OST/%(autonumber)s_%(title)s.%(ext)s'"
alias yost="youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 --yes-playlist -o '/media/raitaro/HDD/Muzica/Anime/OST/%(title)s.%(ext)s'"
alias ydl="youtube-dl"
alias yamv="youtube-dl -o '/media/raitaro/HDD/Muzica/Anime/AMV/%(title)s.%(ext)s'"

# Moving around
alias amv="cd /media/raitaro/HDD/Muzica/Anime/AMV/"
alias ost="cd /media/raitaro/HDD/Muzica/Anime/OST/"


. /home/raitaro/torch/install/bin/torch-activate
